---
# The main playbook to set up installation server

- hosts: inst_servers
#  user: root
  connection: local
  sudo: True

  pre_tasks:
   - name: обновление списка пакетов
     apt: update_cache=yes

  roles:
   - common
