---
# The main playbook to set up installation server

- hosts: inst_servers
#  user: root
  connection: local
  sudo: True

  pre_tasks:
   - name: обновление списка пакетов
     apt: update_cache=yes

  roles:
   - common

  post_tasks:
   - name: перезапуск службы apache2
     service: name=apache2 state=restarted
     tags: remove_dhcp_leases

   - name: перезапуск службы dnsmasq
     service: name=dnsmasq state=restarted
     tags: remove_dhcp_leases
