---
# uninstall server for preseed install OS

- hosts: inst_servers
#  user: root
  connection: local
  sudo: True
  vars_files: ['group_vars/all']

  tasks:
    - name: удаление пакетов
      apt: pkg={{ item }} state=absent purge=yes
      with_items: [apache2, tftpd-hpa, tftp-hpa, dnsmasq, vsftpd]

    - name: удаление ссылок на tftp
      file: path={{ item }} state=absent
      with_items: [ $http.link_to_packages_mirror, $http.link_to_tftp_files]

    - name: удаление каталога tftp
      file: path={{ path_to_tftp_files }} state=absent

