#
# © ОАО «Северное ПКБ», 2014
#
---
    - name: удаление файлов репозитория Astra Linux
      command: rm -rf {{ ftp.path_to_ftp_root }}/{{ ftp.astra_rep_name }}
               removes={{ ftp.path_to_ftp_root }}/{{ ftp.astra_rep_name }}
      when: ftp.astra_rep_name is defined and ftp.src_with_astra_rep is defined
      tags: astra_rep

    - name: создание каталога для репозитория Astra Linux
      command: mkdir {{ ftp.path_to_ftp_root }}/{{ ftp.astra_rep_name }}
      when: ftp.astra_rep_name is defined and ftp.src_with_astra_rep is defined
      tags: astra_rep

    - name: удаление файлов репозитория devel Astra Linux
      command: rm -rf {{ ftp.path_to_ftp_root }}/{{ ftp.dev_astra_rep_name }}
               removes={{ ftp.path_to_ftp_root }}/{{ ftp.dev_astra_rep_name }}
      when: ftp.dev_astra_rep_name is defined and ftp.src_with_dev_astra_rep is defined
      tags: dev_astra_rep

    - name: создание каталога для репозитория devel Astra Linux
      command: mkdir {{ ftp.path_to_ftp_root }}/{{ ftp.dev_astra_rep_name  }}
      when: ftp.dev_astra_rep_name is defined and ftp.src_with_dev_astra_rep is defined
      tags: dev_astra_rep

    - name: удаление файлов репозитория ПК КВГ
      command: rm -rf {{ ftp.path_to_ftp_root }}/{{ ftp.hac_rep_name }}
               removes={{ ftp.path_to_ftp_root }}/{{ ftp.hac_rep_name }}
      when: ftp.hac_rep_name is defined and ftp.src_with_hac_rep is defined
      tags: hac_rep
      
    - name: создание каталога для репозитория ПК КВГ
      command: mkdir {{ ftp.path_to_ftp_root }}/{{ ftp.hac_rep_name }}
      when: ftp.hac_rep_name is defined and ftp.src_with_hac_rep is defined
      tags: hac_rep

    - name: копирование файлов репозитория Astra Linux
      shell: cp -pfR {{ ftp.src_with_astra_rep }}/{{ item }}/ {{ ftp.path_to_ftp_root }}/{{ ftp.astra_rep_name }}/
      when: ftp.astra_rep_name is defined and ftp.src_with_astra_rep is defined
      with_items: [dists, pool]
      tags: astra_rep

    - name: копирование файлов репозитория devel Astra Linux
      shell: cp -pfR {{ ftp.src_with_dev_astra_rep }}/{{ item }}/ {{ ftp.path_to_ftp_root }}/{{ ftp.dev_astra_rep_name }}/
      when: ftp.dev_astra_rep_name is defined and ftp.src_with_dev_astra_rep is defined
      with_items: [dists, pool]
      tags: dev_astra_rep
               
    - name: копирование файлов репозитория ПК КВГ
      command: cp -pfR {{ ftp.src_with_hac_rep }}/{{ item }}/ {{ ftp.path_to_ftp_root }}/{{ ftp.hac_rep_name }}/
      when: ftp.hac_rep_name is defined and ftp.src_with_hac_rep is defined
      with_items: [conf, db, dists, pool]
      tags: hac_rep

