#
# © ООО «Лаборатория 50», 2014, 2015
#
---
    - name: создание каталогов для tftp
      file: path={{ tftp.path }}/pxelinux.cfg state=directory owner=dnsmasq mode=0755

    - copy: src=se15/initrd.gz dest={{ tftp.path }} owner=dnsmasq mode=0644
    - copy: src=se15/linux dest={{ tftp.path }} owner=dnsmasq mode=0644
    - copy: src=se15/pxelinux.0 dest={{ tftp.path }} owner=dnsmasq mode=0644

    - name: создание файла c конфигурацией tftp
      template: src=tftp.conf.j2 dest={{ tftp.path }}/pxelinux.cfg/default
                owner=dnsmasq mode=0644
      when: dhcp.static_mode is not defined or dhcp.static_mode == false

#    - name: создание файла автоматической установки для tftp
#      template: src={{ default_preseed }} dest={{ tftp_path }}/{{ default_preseed }}
#                owner=dnsmasq mode=0644

    - name: чистка старых настроек
      shell: rm -f {{ tftp.path }}/pxelinux.cfg/01-*

    - name: создание файлов конфигурации tftp по mac адресам
      template: src=tftp.conf.j2 dest={{ tftp.path }}/pxelinux.cfg/01-{{ item.1|replace(':','-') }}
                owner=dnsmasq mode=0644
      with_subelements:
       - machines_by_mac
       - mac
      when: machines_by_mac is defined

#    - name: создание preseed файлов по mac адресам
#      template: src={{ item.preseed|default('{{default_preseed}}') }}
#                dest={{ tftp_path }}/{{ item.preseed|default('{{default_preseed_filename}}')|replace('.j2','') }}
#                owner=dnsmasq
#                mode=0644
#      with_items: machines_by_mac
#      when: machines_by_mac is defined

