#
# © ООО «Лаборатория 50», 2014
#
---
    - name: установка пакета vsftpd
      apt: pkg=vsftpd state=latest force=yes

    - name: создание корневой папки для vsftpd
      file: path={{ repos.path }} mode=775 state=directory

    - name: изменение домашнего директория системного пользователя ftp
      command: usermod -d {{ repos.path }} ftp

    - name: создание файла конфигурации для vsftpd
      template: src=vsftpd.conf.j2 dest=/etc/vsftpd.conf

    - name: перезапуск vsftpd
      service: name=vsftpd state=restarted enabled=yes
